baseURL = "https://example.org/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "xmin"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "Categories"
  url = "categories/"
  weight = 3
[[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 4

[params]
  description = "A website built through Hugo."
  footer = "&copy; Mustafa Bhotvawala 2025 | [Github](https://github.com/mustafaabbs2)"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      blockDelimiters = [ ["[", "]"], ["$$", "$$"] ]
      inlineDelimiters = [ ["(", ")"] ]
