baseURL = "https://mustafaabbs2.github.io/"
languageCode = "en-us"
title = "Erkenntnis"
theme = "xmin"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "Travel"
  url = "travel/"
  weight = 3
[[menu.main]]
  name = "Categories"
  url = "categories/"
  weight = 4


[params]
  description = "A website built through Hugo."
  footer = "&copy; Mustafa Bhotvawala 2025 | [Github](https://github.com/mustafaabbs2)"
  favicon = "about/logo_small.ico"

[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "git@github.com:mustafaabbs2/mustafaabbs2.github.io.git"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      blockDelimiters = [ ["[", "]"], ["$$", "$$"] ]
      inlineDelimiters = [ ["(", ")"] ]
